### ISSUE TITLE
Codespace creation fails

### ISSUE THREAD

**Issue by aborigene** [dynatrace-perfclinics/platform-engineering-demo#31]
**Describe the bug**
Upon following the instructions the codespace creation fails with this error:
=================================================================================
2024-09-24 17:44:01.180Z: Creating container...
2024-09-24 17:44:01.238Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/platform-engineering-demo --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --skip-post-create --config "/var/lib/docker/codespacemount/workspace/platform-engineering-demo/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
2024-09-24 17:44:01.543Z: @devcontainers/cli 0.68.0. Node.js v18.20.4. linux 6.8.0-1014-azure x64.
2024-09-24 17:44:01.799Z: $ docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1727199841791/Dockerfile-with-features -t vsc-platform-engineering-demo-f5f210d912d5fdc604e1d4eba600d4f38d4aef02204a7a50a0d2a9b457f1d7be --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=kind /var/lib/docker/codespacemount/workspace/platform-engineering-demo/.devcontainer
2024-09-24 17:44:05.475Z: ERROR: failed to receive status: rpc error: code = Canceled desc = context canceled
2024-09-24 17:44:05.489Z: Stop: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1727199841791/Dockerfile-with-features -t vsc-platform-engineering-demo-f5f210d912d5fdc604e1d4eba600d4f38d4aef02204a7a50a0d2a9b457f1d7be --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=kind /var/lib/docker/codespacemount/workspace/platform-engineering-demo/.devcontainer
2024-09-24 17:44:05.492Z: {"outcome":"error","message":"Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1727199841791/Dockerfile-with-features -t vsc-platform-engineering-demo-f5f210d912d5fdc604e1d4eba600d4f38d4aef02204a7a50a0d2a9b457f1d7be --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=kind /var/lib/docker/codespacemount/workspace/platform-engineering-demo/.devcontainer","description":"An error occurred building the image."}
2024-09-24 17:44:05.492Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1727199841791/Dockerfile-with-features -t vsc-platform-engineering-demo-f5f210d912d5fdc604e1d4eba600d4f38d4aef02204a7a50a0d2a9b457f1d7be --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=kind /var/lib/docker/codespacemount/workspace/platform-engineering-demo/.devcontainer
2024-09-24 17:44:05.492Z:     at FtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:466:1933)
2024-09-24 17:44:05.492Z:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-09-24 17:44:05.493Z:     at async Pm (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:1896)
2024-09-24 17:44:05.496Z:     at async NH (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:610)
2024-09-24 17:44:05.503Z:     at async YtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:3771)
2024-09-24 17:44:05.504Z:     at async eB (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:4886)
2024-09-24 17:44:05.504Z:     at async prA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:663:200)
2024-09-24 17:44:05.504Z:     at async drA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:662:14706)
2024-09-24 17:44:05.517Z: devcontainer process exited with exit code 1

====================================== ERROR ====================================
2024-09-24 17:44:05.527Z: Failed to create container.
=================================================================================
2024-09-24 17:44:05.527Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1727199841791/Dockerfile-with-features -t vsc-platform-engineering-demo-f5f210d912d5fdc604e1d4eba600d4f38d4aef02204a7a50a0d2a9b457f1d7be --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=kind /var/lib/docker/codespacemount/workspace/platform-engineering-demo/.devcontainer
2024-09-24 17:44:05.531Z: Error code: 1302 (UnifiedContainersErrorFatalCreatingContainer)

**To Reproduce**
1. Go to '...' on create codespace
2. Click on 'new with options'
3. Fill with information
4. Creation error appears

**Expected behavior**
The codespace to be created successfully

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 130.0.1

**Comment by aborigene** [comment]
It was because of using a 2 core VM. Switching to 4 core, solved the issue.
